# Generated by Django 4.2.4 on 2023-09-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_travellor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Travellor',
            new_name='Photo',
        ),
    ]
